# Use a Python slim image for lightweight container
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Copy the entire application
COPY . .

# Install dependencies using uv
RUN uv sync --locked

# Expose the port (default 8000, but you can change this when running the container)
EXPOSE 8000

# Use uvicorn to run the app
CMD ["/bin/sh", "-c", "/app/.venv/bin/uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
